### ISSUE TITLE
Game 2 refresh problem

### ISSUE THREAD

**Issue by benjamindonbell** [brinks92/Ghosted#2]
Game 2 is refreshing to the home page and not right back to the game 2 page

**Comment by benjamindonbell** [comment]
Don't worry guys I got this one.
@brinks92 - could you look at this?

**Comment by benjamindonbell** [comment]
Don't worry guys I got this one.
@jc-hayes  - could you look at this?

**Comment by MikeTheGreat** [comment]
This is definitely a bug!

**Comment by jc-hayes** [comment]
Fixed: Put all the game logic in the POST method of the controller and then added client side code. - Ben B.
